- hosts: slrabbitmqbase
  user: smartlis
  become: yes
  become_method: sudo
  tasks:
    - name: Enable the rabbitmq_management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled

    - name: Create "/etc/rabbitmq/rabbitmq.config" file
      copy:
        content: ""
        dest: /etc/rabbitmq/rabbitmq.config
        force: no
        group: sys
        owner: root
        mode: 0777

    - name: Configure rabbitmq.config file
      lineinfile:
        path: /etc/rabbitmq/rabbitmq.config
        line: '[{rabbit, [{loopback_users,[]},{hipe_compile,true}]}].'

    - name: Restart rabbitmq service
      service:
        name: rabbitmq-server
        state: restarted
