- hosts: slrabbitmqbase
  user: smartlis
  become: yes
  become_method: sudo
  tasks:
    
    - name: add erlang repo key
      apt_key:
        url: https://packages.erlang-solutions.com/debian/erlang_solutions.asc
        state: present
        
    - name: add erlang repo
      apt_repository:
        repo: deb https://packages.erlang-solutions.com/ubuntu xenial contrib
        state: present
    
    - name: apt update
      become: yes
      apt:
        update_cache: yes
     
    - name: Install erlang
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - erlang-nox=1:20.1-1 
        - erlang-base-hipe=1:20.1-1 
        - erlang-asn1=1:20.1-1
        - erlang-corba=1:20.1-1
        - erlang-crypto=1:20.1-1
        - erlang-diameter=1:20.1-1 
        - erlang-edoc=1:20.1-1 
        - erlang-eldap=1:20.1-1 
        - erlang-erl-docgen=1:20.1-1 
        - erlang-eunit=1:20.1-1 
        - erlang-ic=1:20.1-1 
        - erlang-inets=1:20.1-1 
        - erlang-inviso=1:20.1-1 
        - erlang-mnesia=1:20.1-1 
        - erlang-odbc=1:20.1-1 
        - erlang-os-mon=1:20.1-1 
        - erlang-parsetools=1:20.1-1 
        - erlang-percept=1:20.1-1 
        - erlang-public-key=1:20.1-1 
        - erlang-runtime-tools=1:20.1-1 
        - erlang-snmp=1:20.1-1 
        - erlang-ssh=1:20.1-1 
        - erlang-ssl=1:20.1-1 
        - erlang-syntax-tools=1:20.1-1 
        - erlang-tools=1:20.1-1 
        - erlang-xmerl=1:20.1-1
        
    - name: Hold erlang package version
      become: yes
      shell: apt-mark hold erlang-nox=1:20.1-1 erlang-base-hipe=1:20.1-1 erlang-asn1=1:20.1-1 erlang-corba=1:20.1-1 erlang-crypto=1:20.1-1 erlang-diameter=1:20.1-1 erlang-edoc=1:20.1-1 erlang-eldap=1:20.1-1 erlang-erl-docgen=1:20.1-1 erlang-eunit=1:20.1-1 erlang-ic=1:20.1-1 erlang-inets=1:20.1-1 erlang-inviso=1:20.1-1 erlang-mnesia=1:20.1-1 erlang-odbc=1:20.1-1 erlang-os-mon=1:20.1-1 erlang-parsetools=1:20.1-1 erlang-percept=1:20.1-1 erlang-public-key=1:20.1-1 erlang-runtime-tools=1:20.1-1 erlang-snmp=1:20.1-1 erlang-ssh=1:20.1-1 erlang-ssl=1:20.1-1 erlang-syntax-tools=1:20.1-1 erlang-tools=1:20.1-1 erlang-xmerl=1:20.1-1
        
      
