- hosts: slrabbitmqbase
  user: smartlis
  become: yes
  become_method: sudo
  tasks:

    - name: Install rabbitmq
      apt: 
        name: rabbitmq-server
        state: present

    - name: check rabbitmq is started
      service:
        name: rabbitmq-server
        state: started
